#!/bin/sh

# Set these paths appropriately

BIN=/home/khairunnisa/TreeTagger/bin
CMD=/home/khairunnisa/TreeTagger/cmd
LIB=/home/khairunnisa/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/bulgarian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
