#!/bin/sh

# Set these paths appropriately

BIN=/home/khairunnisa/TreeTagger/bin
CMD=/home/khairunnisa/TreeTagger/cmd
LIB=/home/khairunnisa/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
